### ISSUE TITLE
Merge into hashicorp/hcl

### ISSUE THREAD

**Issue by phinze** [hashicorp/hcl2#115]
Now that Terraform 0.12 is using HCL2 - we can merge this repo over to the main `hashicorp/hcl` location.

**Comment by xkisu** [comment]
Any chance of this happening soon? I'd like to use some of the HCL2 features in a program for work but I'm hesitant to use before there's any versioning of the library implemented.

**Comment by apparentlymart** [comment]
Given how close it is, we are now holding for Go 1.13 so that we can rely on the finalized version of Go Modules to allow both major versions of HCL to be usable at once. There's other work going on which means that we won't be able to start this _immediately_ after Go 1.13 is released, but we're hoping to do it shortly afterward.

**Comment by apparentlymart** [comment]
This is in progress right now. I'm closing this ahead of time to allow for archiving this repository.

For more information, see [Version Selection](https://github.com/hashicorp/hcl/wiki/Version-Selection). This `hcl2` repository will remain here in an archived state for the time being in order to allow existing callers to continue to import it.
