### ISSUE TITLE
Clarification on the future of HCL?

### ISSUE THREAD

**Issue by eschwartz** [hashicorp/hcl2#14]
I'm wondering if the Terraform team could provide some clarification on the future of HCL and HCL2. I haven't seen any official mention of HCL2, and only found out about it via vague references in terraform github issues. These usually sound something like:

> We're not  going to address this critical Terraform bug/deficiency/feature, because we're focusing all of our efforts on a new version of the HCL language. Hopefully, your bug/deficiency/feature will be addressed in HCL2.

On the one hand, I'm very excited about a new version of HCL. As much as I love Terraform, it quickly become clear that the current iteration of HCL is a little rough around the edges. I'd love to put all my hopes and dreams into a promised shiny new version of HCL. 

On the other hand, the prospect of a backwards-incompatible language change kind of freaks me out. Should developers hold off on using Terraform in production until HCL v2 is released? Do we need to budget time a for full rewrite of all existing modules? Will the Terraform team provide some kind of tooling to make the transition smoother?

I hope I'm not coming across as too snarky. I really love Terraform, and despite all of its rough-edges, it is still the best thing out there for what it does. It would just be nice to see some official communication from the Terraform team on this matter, so users can plan accordingly.

Thank you!

**Comment by apparentlymart** [comment]
Hi @eschwartz,

This is more of a Terraform question than it is an HCL question, but I'll answer it here since there seem to be others monitoring this issue.

More details will come once we've had more time to test with existing configurations (happening right now) but broadly-speaking this is the situation:

* The HCL2 parser is _largely_ backwards-compatible with the older HCL parser. A small number of deviations were unavoidable to address ambiguities and limitations of the old syntax, but we've been very careful to ensure that this only affects configurations that use non-idiomatic forms (i.e. not what is shown in documentation) or rely on undocumented implementation details.
  * (To say that a different way: a "full rewrite" will _certainly_ not be necessary. This is just a new implementation of the existing language with some different details/features, not a new language altogether.)
* We plan to release an early preview version of Terraform with the new parser once it's integrated enough to be useful, in the hope that some users are able to try it on examples from their existing configurations (though _not_ on their real environments, yet) to catch any cases that we aren't able to catch with the examples we have access to.
* All issues found in our own testing and via that preview release will be addressed in one of the following ways:
  * Change either the HCL parser or Terraform's config loader to support a new form.
  * Add a transform to the configuration upgrade tool (which indeed we plan to include) to flag the construct and, if possible, automatically fix it.

We've already been doing some "shallow" testing of the parser/loader and have generally found only minor deviations _at the syntax level_ that have been easy to fix. More in-depth testing will follow as the rest of Terraform is updated.

There will be more details about this once we get close to the aforementioned preview release. I'd ask that we have any further discussion about this in the Terraform repository rather than this repository, since this relates primarily to Terraform's transition and not to the HCL language itself, and almost all of the remaining work will actually be in the Terraform repository rather than this one.

**Comment by eschwartz** [comment]
Thank you for responding! This helps ease some of my concerns

**Comment by vfab** [comment]
Are you closing in on a release date for HCL2?  I haven't found any recent updates on HCL2.
