### ISSUE TITLE
Release dates and documentation

### ISSUE THREAD

**Issue by luisdavim** [hashicorp/hcl2#26]
Hi,
any rough idea of a release date yet?
Where can I find documentation for the features being implemented in HCL2?

**Comment by apparentlymart** [comment]
Hi @luisdavim,

I assume when you are asking about "release dates" here you are specifically referring to Terraform's integration of this code, rather than to this code itself. This repository itself won't be "released", since it's just a re-usable library.

More details will be coming soon about the release plan for Terraform 0.12. This will be shared in the context of the Terraform repository rather than here.

The HCL2-level features are captured in [the native syntax spec](https://github.com/hashicorp/hcl2/blob/master/hcl/hclsyntax/spec.md). At the moment the various Terraform changes are documented across a number of separate GitHub issues. The highlights will be summed up as part of the release plan I mentioned above.

**Comment by jippi** [comment]
@apparentlymart as someone who is currently vendoring `hcl` and plan to vendor `hcl2` - it would be very nice to be able to use git tags with `dep` 

Are you not planning to tag "hcl2" releases semver style?
